apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-x2a
  namespace: rhdh
  title: "X2A"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
  tags: []
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-x2a"
  dynamicArtifact: oci://quay.io/x2ansible/red-hat-developer-hub-backstage-plugin-x2a:x2a__0.1.0!red-hat-developer-hub-backstage-plugin-x2a
  version: 0.1.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: community
  lifecycle: active
